chore(refactor): performance improvements
BirthdayResearch/quantum pull request #710
Opened 2023-03-08 08:14 UTC by nattadex

#### What this PR does / why we need it:
Moving the bridge status check api call to a `getServerSideProps()` function

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-03-08 09:16 UTC, kevzzsk commented on apps/web/src/pages/index.tsx
> +    props: { isLoaded, isBridgeUp }, // will be passed to the page component as props
`isBridgeUp` doesn't seem to be used anywhere. in `Home` component seems to only read `isLoaded`.

2023-03-08 09:16 UTC, kevzzsk commented on apps/web/src/pages/index.tsx
> +  const res = await fetch(`https://wallet.defichain.com/api/v0/bridge/status`);
Please add the error case and http error status case for non 200 cases

2023-03-08 10:16 UTC, kevzzsk requested changes

2023-03-08 10:16 UTC, kevzzsk commented on apps/web/src/pages/index.tsx
> +      isBridgeUp = true;
i think you have to flip the logic here, if not `isBridgeUp` will never be `false`.

you need to check `if (data?.isUp === false)` then set `isBridgeUp` to false

2023-03-08 13:49 UTC, nattadex commented on apps/web/src/pages/index.tsx
> +      isBridgeUp = true;
done!

2023-03-08 13:50 UTC, nattadex commented on apps/web/src/pages/index.tsx
> +  const res = await fetch(`https://wallet.defichain.com/api/v0/bridge/status`);
donee!

2023-03-09 01:32 UTC, thedoublejay requested changes

2023-03-09 01:32 UTC, thedoublejay commented on apps/web/src/pages/index.tsx
> +          isBridgeUp = false;
```suggestion
          isBridgeUp = data?.isUp === false;
```

No need for the if statement anymore.

2023-03-09 02:35 UTC, thedoublejay approved these changes

2023-03-09 02:35 UTC, merged