feat(api): ethereum/stats API
BirthdayResearch/quantum pull request #737
Opened 2023-03-10 05:54 UTC by jordankzf

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-03-10 07:05 UTC, kevzzsk commented on apps/server/src/types.ts
> +export type Erc20Token = "WBTC" | "USDT" | "USDC" | "ETH";
there is already supported token list `SupportedEVMTokenSymbols`
https://github.com/BirthdayResearch/quantum/blob/8481ba96a959c66e14a08dd1887067ed74847165/apps/server/src/AppConfig.ts#L59-L64

2023-03-10 07:05 UTC, kevzzsk commented on apps/server/src/types.ts
> +export type ISO8601String = `${number}-${number}-${number}T${number}:${number}:${number}.${number}Z`;
I think we dont need the Time portion of the ISO8601. We can just expect a format of YYYY-MM-DD string

2023-03-10 07:05 UTC, kevzzsk commented on apps/server/src/ethereum/EthereumInterface.ts
> +        [token in Erc20Token]?: number
the value type should not be `number`, it should be `string` because we need to be precise with the DP

2023-03-11 15:44 UTC, jordankzf commented
To-do

- [x] Date filtering
- [x] Target Ethereum table
- [x] Unit tests
- [x] 6 Decimal places
- [x] Cache
- [ ] Manual testing (via real database entries)

2023-03-13 02:21 UTC, kevzzsk commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      date: dateOnly,
I don't think we need to return the `date` back in the response as the request will already have `date` params input from the caller

2023-03-13 02:21 UTC, kevzzsk commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +          throw new Error('API call for Ethereum statistics was unsuccessful', { cause: e });
can you make sure that this throws a http error and return an error message to API ?

2023-03-13 05:32 UTC, pierregee requested changes

2023-03-13 05:32 UTC, pierregee commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      this.prisma.bridgeEventTransactions.findMany({
Can we explore if we can move the token grouping + sum of each confirmed txn in db. A prisma equivalent of this to reduce looping 
```

SELECT bet."tokenSymbol", SUM(CAST (amount AS DECIMAL)) as "sumOfConfirmedTxn" 
FROM "BridgeEventTransactions" bet 
-- WHERE
group BY bet."tokenSymbol"
```

2023-03-13 05:32 UTC, pierregee commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +    tomorrow.setDate(today.getDate() + 1);
```suggestion
    const tomorrow = new Date(today.getDate() + 1);
```

2023-03-13 05:45 UTC, pierregee commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +          status: 'CONFIRMED',
What is the expected return for`confirmedTransactions`? I think we should also check if `sendTransactionHash` column is not null which means that the user received the DFC equivalent of EVM token

2023-03-13 13:15 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      date: dateOnly,
It's for confirmation reasons, especially when we are caching the result. In fact, I wish to alter it so that it returns the timestamp as well. This way, the caller will know how stale the data provided is, since it may be up to 23 hours 59 minutes 59 seconds old.

2023-03-13 13:27 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      this.prisma.bridgeEventTransactions.findMany({
This was my initial implementation.

Something like the following:

`await prisma.bridgeEventTransactions.groupBy({
    by: ['tokenSymbol'],
    _sum: {
      amount: true,
    },
  });`
  
This issue here is that precision is lost due to the way the amounts are summed up internally. Prisma cannot do `BigNumber` operations.

2023-03-13 13:29 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +          status: 'CONFIRMED',
`confirmedTransactions` is the total record/row count of transactions that are successful.

`sendTransactionHash` non-null check has been added.

2023-03-13 13:36 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      date: dateOnly,
Either way, I think it's still good practice to return the queried date, so that the user can verify that the date param was parsed correctly, since we accept any string arbitrarily.

Let me know if you prefer to have it removed.

2023-03-13 13:52 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +    tomorrow.setDate(today.getDate() + 1);
This suggested change overflows the tomorrow const to `1970-01-01T00:00:00.010Z`

It does not seem equivalent.

2023-03-13 14:16 UTC, jordankzf commented
API Definition Documentation updated here: https://docs.google.com/document/d/1W3Vnjd57_D2U24ivBdKihaQRLOogD3RKv4zHovFqCAM/edit

2023-03-14 02:18 UTC, thedoublejay requested changes

2023-03-14 02:18 UTC, thedoublejay commented on apps/server/src/types.ts
> +export type Iso8601DateOnlyString = `${number}-${number}-${number}`;
We shouldn't have this common types. It's a bad practice that might be re-used by other devs and be filled up with mixed data. I suggest we keep it where it's only needed. (Stats module).

2023-03-14 02:18 UTC, thedoublejay commented on apps/server/test-i9n/testing/Statistics.i9n.ts
> +
Same as this, let's move this to a ethereum specific file. If we support more chains in the future, we can have "bitcoin/stats, polygon/stats" etc.

2023-03-14 02:18 UTC, thedoublejay commented on apps/server/src/ethereum/EthereumModule.ts
> +  imports: [EthersModule, CacheModule.register({ max: 10_000 })],
Would this affect other modules under Ethereum? Can we only cache the specifc service/module?

2023-03-14 02:18 UTC, thedoublejay commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +    )) as StatsModel;
Why do we need to cache it? Maybe better to add it on the cache itself? Like this.cache.get<StatsModel>()

2023-03-14 02:33 UTC, thedoublejay requested changes

2023-03-14 02:33 UTC, thedoublejay commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +  async getStats(@Query('date') date?: Iso8601DateOnlyString): Promise<StatsModel> {
Does this work as DTO? https://docs.nestjs.com/techniques/validation

2023-03-14 02:48 UTC, kevzzsk commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      date: dateOnly,
As you mentioned, stale data will only happen on today's date and the purpose of the endpoint is not to provide realtime update but more to allow historical query of data. So I wouldn't be too worried by the stale data for today's query given it is not yet completed.

secondly, about verifying whether the date param was parsed correctly, we should always reject param that does not conform to the specified format YYYY-MM-DD, so user will know always know that the data is always correct and wrong query will not have data.

2023-03-14 05:24 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      date: dateOnly,
1. So you want to remove both `date` and `cacheTime` from the return?
2. This is the current implementation. If you provide the `&date=` without anything, it will be rejected.

2023-03-14 05:26 UTC, jordankzf commented on apps/server/src/ethereum/EthereumModule.ts
> +  imports: [EthersModule, CacheModule.register({ max: 10_000 })],
It should not. `this.cache.get()` must be explicitly called in order to cache the return.

2023-03-14 05:26 UTC, jordankzf commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +    )) as StatsModel;
Yes, it's cached on line 25 via `this.cache.get()`

2023-03-14 05:42 UTC, kevzzsk commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      date: dateOnly,
Yeah, I think `date` and `cacheTime` will not be meaningful for end users

2023-03-14 06:58 UTC, thedoublejay commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +    )) as StatsModel;
Sorry my message was incorrect. My question was why do we need to "typecast" it as StatsModel. Can we do something like cache.get<StatsModel>()

2023-03-14 07:14 UTC, jordankzf commented on apps/server/test-i9n/testing/Statistics.i9n.ts
> +
It's the same pattern used in `VersionController.ts` and `WhaleWalletController.ts`. Let me see if it's possible to avoid typecasting.

2023-03-14 07:47 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      date: dateOnly,
Removed.

2023-03-14 08:15 UTC, jordankzf commented on apps/server/test-i9n/testing/Statistics.i9n.ts
> +
The reason it was typecasted is because `this.cache.get()` can possibly return `undefined`. The return type at its source is defined by `async-mutex`. For this reason, it cannot be edited unless overwritten.

I made this change instead to avoid typecasting:
`async getStats(@Query('date') date?: Iso8601DateOnlyString): Promise<StatsModel | undefined> {`

2023-03-14 08:16 UTC, jordankzf commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +    )) as StatsModel;
The reason it was typecasted is because this.cache.get() can possibly return undefined. The return type at its source is defined by async-mutex. For this reason, it cannot be edited unless overwritten.

I made this change instead to avoid typecasting:
async getStats(@Query('date') date?: Iso8601DateOnlyString): Promise<StatsModel | undefined> {

2023-03-15 02:38 UTC, kevzzsk commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +  async getStats(date?: Iso8601DateOnlyString): Promise<StatsModel> {
can we add a simple sanity check on the date passed in? like rejecting when the date is in the future (more than todays date). This is to prevent useless query reaching our DB

2023-03-15 03:25 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +  async getStats(date?: Iso8601DateOnlyString): Promise<StatsModel> {
Added

2023-03-15 03:54 UTC, jordankzf commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +  async getStats(@Query('date') date?: Iso8601DateOnlyString): Promise<StatsModel> {
Converted to DTO

2023-03-15 04:09 UTC, jordankzf commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +          return new StatsDto(statsModel);
I _think_ this is how DTO validation is done, not entirely sure.

CC: @thedoublejay @nattadex

2023-03-15 04:26 UTC, thedoublejay commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +          return new StatsDto(statsModel);
Looks ok!

2023-03-15 04:28 UTC, thedoublejay requested changes

2023-03-15 04:28 UTC, thedoublejay commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +          return new StatsDto(statsModel);
Why do we need to have a StatsDto? It looks like it's the same as StatsModel?

2023-03-15 05:55 UTC, kevzzsk requested changes

2023-03-15 05:55 UTC, kevzzsk commented on apps/server/.eslintignore
> +src/types.ts
this should not be needed anymore right

2023-03-15 05:55 UTC, kevzzsk commented on apps/server/src/utils/StatsUtils.ts
> +export type Iso8601String = `${number}-${number}-${number}T${number}:${number}:${number}.${number}Z`;
this should also not be used anymore

2023-03-15 05:55 UTC, kevzzsk commented on apps/server/test-i9n/testing/ethereum/Statistics.i9n.ts
Could you also add the case where user input a future date?

2023-03-15 06:12 UTC, jordankzf commented on apps/server/.eslintignore
> +src/types.ts
removed

2023-03-15 06:13 UTC, jordankzf commented on apps/server/src/utils/StatsUtils.ts
> +export type Iso8601String = `${number}-${number}-${number}T${number}:${number}:${number}.${number}Z`;
removed

2023-03-15 06:50 UTC, jordankzf commented on apps/server/test-i9n/testing/ethereum/Statistics.i9n.ts
added

2023-03-15 06:51 UTC, jordankzf commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +          return new StatsDto(statsModel);
Removed!

2023-03-15 07:33 UTC, kevzzsk requested changes

2023-03-15 07:33 UTC, kevzzsk commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +    const dateFrom = new Date(dateOnly as string);
we also need to take care of `date` is a valid date string? because if we pass like `2023-00-00` it will pass the format check but it is not a valid date. It will probably cause server error.

maybe add this to the test too

2023-03-15 07:33 UTC, kevzzsk commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +          // const statsModel = await this.evmTransactionConfirmerService.getStats(date);
we can remove not needed comments too

2023-03-15 09:28 UTC, jordankzf commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +    const dateFrom = new Date(dateOnly as string);
`ethereum/stats?date=2023-00-00` returns `{"status":500,"error":"API call for Ethereum statistics was unsuccessful: Invalid time value"}`

JS's native `Date` object constructor will fail if `date` is not valid, and the `try...catch` statement which wraps the `getCache()` method gracefully handles this exception.

I used this design pattern so that the error will not be cached. The resulting payload will only be cached if it was computed successfully.

2023-03-15 09:28 UTC, jordankzf commented on apps/server/src/ethereum/controllers/EthereumController.ts
> +          // const statsModel = await this.evmTransactionConfirmerService.getStats(date);
removed

2023-03-15 09:35 UTC, kevzzsk approved these changes

2023-03-16 01:53 UTC, thedoublejay approved these changes

2023-03-16 01:54 UTC, merged