Nicole/bridge defichain stats
BirthdayResearch/quantum pull request #750
Opened 2023-03-14 02:32 UTC by nattadex

#### What this PR does / why we need it:
creating an api endpoint for displaying defichain stats 

#### Which issue(s) does this PR fixes?:
https://birthday.atlassian.net/browse/EB-38

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-03-15 04:12 UTC, jordankzf commented on apps/server/src/defichain/model/StatsDto.ts
> +  date?: Date;
The `Date` object defined here is not interchangeable with an `ISO 8601` string.

2023-03-15 04:19 UTC, jordankzf commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +    if (tokenSymbol && claimAmount !== null) {
Is there a reason nullity is checked here instead of within the prisma query?

2023-03-15 04:22 UTC, jordankzf commented on apps/server/test-i9n/defichain/stats.i9n.ts
> +    expect(JSON.parse(initialResponse.payload).date).toStrictEqual(targetDate);
Tests need updating, `date` and `cacheTime` are no longer returned as per discussion here: https://github.com/BirthdayResearch/quantum/pull/737#pullrequestreview-1336152179.

Looks like you've already removed them in the service, just a gentle reminder 🙏

2023-03-15 04:23 UTC, jordankzf commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +    const today = new Date(dateOnly.toString());
Renaming `today` and `tomorrow` to `dateFrom` and `dateTo` might make more sense since the user can specify a date in the query.

2023-03-15 04:24 UTC, jordankzf commented on apps/server/src/defichain/controllers/StatsController.ts
> +    )) as DeFiChainStats;
JJ suggested for this typecast to be removed. Discussion here: https://github.com/BirthdayResearch/quantum/pull/737#pullrequestreview-1338313617

Updating `Promise<DeFiChainStats>` to `Promise<DeFiChainStats | undefined>` should do the trick.

2023-03-15 04:27 UTC, jordankzf commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +    const dateOnly = date ?? new Date();
Please add a sanity check. Discussion: https://github.com/BirthdayResearch/quantum/pull/737#pullrequestreview-1340553304

2023-03-15 04:38 UTC, nattadex commented on apps/server/test-i9n/defichain/stats.i9n.ts
> +    expect(JSON.parse(initialResponse.payload).date).toStrictEqual(targetDate);
im not returning `date` or `cacheTime` anywhere tho LOL but ok thx

2023-03-15 04:42 UTC, jordankzf commented on apps/server/src/defichain/controllers/StatsController.ts
> +import { SemaphoreCache } from 'src/libs/caches/SemaphoreCache';
Your tests are failing for these two reasons:
1. Main branch is broken 🥲 `test-i9n/defichain/verify.i9n.ts` CI test runners 1 & 2 should fail for this reason.
2. Our path resolution is borked, you may have to use double dot notation (e.g. `../libs/caches/SemaphoreCache`) in some places instead, so that the targeted import can be resolved correctly.

You may refer to this commit: https://github.com/BirthdayResearch/quantum/commit/9133253b4bd37d33ae3d91a0fe4d63dfc837c712

2023-03-15 05:47 UTC, nattadex commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +    if (tokenSymbol && claimAmount !== null) {
okiee, changed!

2023-03-15 05:51 UTC, nattadex commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +    const today = new Date(dateOnly.toString());
done!

2023-03-15 05:54 UTC, nattadex commented on apps/server/src/defichain/controllers/StatsController.ts
> +    )) as DeFiChainStats;
okiee

2023-03-15 06:44 UTC, nattadex commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +    const dateOnly = date ?? new Date();
donezo

2023-03-15 06:44 UTC, nattadex commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +    const dateOnly = date ?? new Date();
donezo

2023-03-15 06:56 UTC, nattadex commented on apps/server/src/defichain/model/StatsDto.ts
> +  date?: Date;
done!

2023-03-15 07:38 UTC, kevzzsk requested changes

2023-03-15 07:38 UTC, kevzzsk commented on apps/server/src/defichain/controllers/StatsController.ts
> +// import { stats } from '@defichain/whale-api-client';
lets remove comments that are not necessary

2023-03-15 07:38 UTC, kevzzsk commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +  return amountBridgedToDfc;
as mentioned, this is the amount bridge out of DFC into EVM

2023-03-15 09:35 UTC, nattadex commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +  return amountBridgedToDfc;
changed naming

2023-03-15 09:35 UTC, nattadex commented on apps/server/src/defichain/DefichainInterface.ts
> +export type BridgedEvmToDfc = Record<SupportedDFCTokenSymbols, string>;
changed!

2023-03-16 02:34 UTC, kevzzsk requested changes

2023-03-16 02:34 UTC, kevzzsk commented on apps/server/src/defichain/DefichainInterface.ts
> +export type Iso8601DateOnlyString = `${number}-${number}-${number}`;
with Jordan's PR merged. you can merge main and remove this and import from Jordan's changes

2023-03-16 02:34 UTC, kevzzsk commented on apps/server/test-i9n/defichain/stats.i9n.ts
> +      url: `/ethereum/stats?date=`,
this url should be `/defichain`

2023-03-16 02:34 UTC, kevzzsk commented on apps/server/src/defichain/DefichainInterface.ts
also seemed that Jordan has updated his version of this interface.

https://github.com/BirthdayResearch/quantum/blob/7a815e1360ebc49b6ff8f9af4d464ee97a817d7b/apps/server/src/ethereum/EthereumInterface.ts#L6-L40

2023-03-16 02:49 UTC, nattadex commented on apps/server/src/defichain/DefichainInterface.ts
> +export type Iso8601DateOnlyString = `${number}-${number}-${number}`;
okie!

2023-03-16 02:49 UTC, nattadex commented on apps/server/test-i9n/defichain/stats.i9n.ts
> +      url: `/ethereum/stats?date=`,
done!

2023-03-16 02:53 UTC, nattadex commented on apps/server/src/defichain/DefichainInterface.ts
donezooo!

2023-03-16 03:16 UTC, kevzzsk requested changes

2023-03-16 03:16 UTC, kevzzsk commented on apps/server/test-i9n/defichain/stats.i9n.ts
> +import { DeFiChainStats } from 'dist/defichain/DefichainInterface';
I think you imported wrongly? shouldn't be from `dist` folder

2023-03-16 03:51 UTC, thedoublejay requested changes

2023-03-16 03:51 UTC, thedoublejay commented on apps/server/src/defichain/DefichainInterface.ts
> +      USDC: amountBridged[SupportedDFCTokenSymbols.USDC]?.toString(),
Should we have any default values here all fallbacks? Like change it to zero or something

2023-03-16 03:51 UTC, thedoublejay commented on apps/server/src/defichain/controllers/StatsController.ts
> -  async get(): Promise<stats.StatsData> {
let's not removed this, maybe put it into another endpoint

2023-03-16 04:28 UTC, nattadex commented on apps/server/src/defichain/controllers/StatsController.ts
> -  async get(): Promise<stats.StatsData> {
ok!

2023-03-16 04:29 UTC, nattadex commented on apps/server/src/defichain/DefichainInterface.ts
> +      USDC: amountBridged[SupportedDFCTokenSymbols.USDC]?.toString(),
okie, set the default value as '0.000000'

2023-03-16 04:39 UTC, pierregee requested changes
Can we add an e2e for the actual full flow - happy path? 
1. Bridge DFC -> EVM then the amount should reflect on the stats
2. Should we add an e2e that the stats are cached?

2023-03-16 06:04 UTC, lykalabrada commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +  for (const key in amountBridgedBigN) {
Can we use forEach here?
```
Object.keys(amountBridgedBigN).forEach((key) => {
    amountBridgedToEVM[key as SupportedDFCTokenSymbols] = amountBridgedBigN[key as SupportedDFCTokenSymbols].decimalPlaces(6, BigNumber.ROUND_FLOOR).toString() 
  })
```

2023-03-16 06:37 UTC, nattadex commented on apps/server/src/defichain/services/DeFiChainStatsService.ts
> +  for (const key in amountBridgedBigN) {
yesss!

2023-03-16 07:54 UTC, thedoublejay requested changes

2023-03-16 07:54 UTC, thedoublejay commented on apps/server/src/defichain/DefichainInterface.ts
> +      USDC: amountBridged[SupportedDFCTokenSymbols.USDC]?.toString() || '0.000000',
Store this on a new BigNumber then just use default.

const defaultValue = new BigNumber(0).toFixed(6)

2023-03-16 07:54 UTC, thedoublejay commented on apps/server/src/defichain/controllers/StatsController.ts
> +  @Get('/clientStats')
```suggestion
  @Get('/whale/stats')
```

2023-03-16 08:03 UTC, nattadex commented on apps/server/src/defichain/DefichainInterface.ts
> +      USDC: amountBridged[SupportedDFCTokenSymbols.USDC]?.toString() || '0.000000',
oki

2023-03-16 08:03 UTC, nattadex commented on apps/server/src/defichain/controllers/StatsController.ts
> +  @Get('/clientStats')
done!

2023-03-17 03:23 UTC, pierregee approved these changes

2023-03-17 03:23 UTC, lykalabrada approved these changes

2023-03-17 03:33 UTC, kevzzsk approved these changes

2023-03-17 03:47 UTC, thedoublejay approved these changes

2023-03-17 03:47 UTC, merged