feature(ui-ux): refetch hot wallet balance and transfer guard
BirthdayResearch/quantum pull request #763
Opened 2023-03-17 03:04 UTC by G9000

#### What this PR does / why we need it:
To ensure balance value are up to date when verify transfer is clicked and prevent user to proceed if the balance is insufficient.

#### Which issue(s) does this PR fixes?:

Fixes #758

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-03-17 07:57 UTC, pierregee requested changes

2023-03-17 07:57 UTC, pierregee commented on apps/web/src/components/BridgeForm.tsx
> +  async function verifyTransfer(refetch?: boolean) {
```suggestion
  async function verifySufficientHWBalance(
    refetch?: boolean
  ): Promise<boolean | undefined> {
```
Is this func name better? verifyTransfer sounds a bit generic

2023-03-17 07:57 UTC, pierregee commented on apps/web/src/components/BridgeForm.tsx
> +    const verify = await verifyTransfer(true);
```suggestion
    const isBalanceSufficient = await verifySufficientHWBalance(true);
    if (!isBalanceSufficient) {
       setIsVerifyingTransaction(false);
       return
    }
```

2023-03-17 07:57 UTC, pierregee commented on apps/web/src/components/BridgeForm.tsx
> +  async function getBalanceFn() {
can add some typescript for the result, if possible

2023-03-17 07:57 UTC, pierregee commented on apps/web/src/components/BridgeForm.tsx
> +    getBalanceFn();
hmm could you also check why linting is not throwing error/warning on this?, promises should have await right?

2023-03-17 07:57 UTC, pierregee commented on apps/web/src/components/BridgeForm.tsx
> +    const balance = refetch ? refetchBalance[key] : tokenBalances[key];
```suggestion
   const balance = (refetch ? await getBalanceFn() : tokenBalances)[key];
```
hmm is this better? I noticed that the second ternary operator isn't necessary

2023-03-17 08:08 UTC, G9000 commented on apps/web/src/components/BridgeForm.tsx
> +    const balance = refetch ? refetchBalance[key] : tokenBalances[key];
haha preference :v :v i guess

2023-03-17 08:15 UTC, G9000 commented on apps/web/src/components/BridgeForm.tsx
> +    const verify = await verifyTransfer(true);
already declared on top. So instead i change to isBalanceSufficientVerified?

2023-03-20 01:47 UTC, pierregee requested changes

2023-03-20 01:47 UTC, pierregee commented on apps/web/src/components/BridgeForm.tsx
> +          return;
If this if condition is satisfied, button will not be enabled again
```suggestion
          setIsVerifyingTransaction(false);
          return;
```

2023-03-20 05:24 UTC, JoshuaC817 commented
LGTM!

2023-03-23 01:38 UTC, pierregee approved these changes

2023-03-23 01:39 UTC, merged